--- #this specifies it is a yaml file
name: Checks

on: [push] #will trigger after each github push

jobs:
  test-lint:
    name: Test and Lint #job id
    runs-on: ubuntu-20.04 #container will run using this OS
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1 #builtin action to login dockerhub
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2 #action for accessing code from github
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py test"
      # - name: Linting #checking synatx
      #   run: docker-compose run --rm app sh -c "flake8"